name: Build documentation

# Currently not automatically triggered because Github's automatic pages workflow interferes
on:
  workflow_dispatch:

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.x'

      - name: Install pdoc
        run: pip install pdoc
        
      - name: Generate Documentation
        run: pdoc -o docs/ ./src/fairreckitlib  

      - name: Package Documentation
        run: tar --directory docs/ -hcf artifact.tar .

      - name: Upload Documentation Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./artifact.tar
  
  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
