# Lints only in modified files
name: Partial Pylint

on:
  pull_request:
    branches:
      - dev

jobs:
  lintchanges:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Retrieve and lint changed files
    outputs: 
      files: steps.changedfiles.changed-files.outputs
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.7
        with:
          files: |
            **/*.py
          files_ignore: |
            !**.py
            
      - name: Any changes?
        run: |
          echo "${{ steps.changed-files.outputs.any_changed }}"
      
      - name: Install dependencies
        run: |
          if ${{ steps.changed-files.outputs.any_changed }}; then
            python -m pip install --upgrade pip
            pip install pylint
            pip install pytest
            pip install lenskit
            pip install implicit
            pip install Cython
            pip install scikit-surprise
            pip install pandas
            pip install PyYAML
            pip install rexmex
            pip install h5py
          fi
          
      - name: Lint all changed files
        run: |
          if ${{ steps.changed-files.outputs.any_changed }}; then
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              pylint --disable=R0913,C0103,R0903,W0611,W0105,C0321,W0511,R0902,C0301,W0613 --exit-zero $file
            done
          fi
