# Lints only in modified files
name: Partial Pylint

on:
  pull_request:
    branches:
      - dev

jobs:
  lintchanges:
    runs-on: ubuntu-latest #runs-on: ubuntu-latest | windows-latest | macos-latest
    name: Retrieve and lint changed files
    outputs: 
      files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch enough history to detect changes

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.7
        with:
          files: |
            **/*.py
          files_ignore: |
            !**.py
            
      - name: Any changes?
        run: |
          echo "${{ steps.changed-files.outputs.any_changed }}"
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Lint all changed Python files
        run: |
          # Save the output of the changed files
          echo "changed_files=${{ steps.changed-files.outputs.all_changed_files }}" >> $GITHUB_STATE
          
          # Lint each file and capture any errors
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            pylint --disable=R0913,W0511,W0613 $file
          done
          exit $exit_code
