name: PEP257

on:
  workflow_dispatch:
  pull_request:
    branches:
      - stable
      - dev

jobs:
  doc-check:
    name: Analyse docstrings
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
        
    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pydocstyle
        
    - name: Analysing the code with pydocstyle
      run: pydocstyle $(git ls-files '*.py')
