name: Pylint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - stable
  schedule:
    - cron: 0 0 * * *

jobs:
  full-lint:
    name: Full Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version: '3.9.x'
        
    #- uses: actions/cache@v4
    #  with:
    #    path: ${{ env.pythonLocation }}
    #    key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

    - name: Force install pip 23.2.1 using get-pip.py
      run: |
        curl -sS https://bootstrap.pypa.io/pip/get-pip.py -o get-pip.py
        python get-pip.py pip==23.2.1

    - name: Confirm pip version
      run: pip --version

    - name: Install dependencies
      run: pip install -r requirements.txt
        
    - name: Analysing the code with pylint
      run: pylint $(git ls-files '*.py') --fail-under=9 --fail-on=E
