name: Pylint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - stable
  schedule:
    - cron: 0 0 * * *

jobs:
  full-lint:
    name: Full Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
        
    - uses: actions/cache@v4
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Analysing the code with pylint
      run: pylint $(git ls-files '*.py') --fail-under=9 --fail-on=E
