# Uploads the library as a package to TestPyPI and PyPI
name: Upload to PyPI

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-n-publish:
    name: Build Python distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9.x'
        
    - name: Install pypa/build
      run: >-
        python -m 
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: Publish Python distribution to PyPI
    #if: startsWith(github.ref, 'refs/tags/')  # Only publish to PyPI on tag pushes
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/fairreckitlib
    permissions:
      id-token: write  # Mandatory for trusted publishing
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish package on Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN_FAIRRECKIT }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish package on PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN_FAIRRECKIT }}
