name: Pytest with Coverage

on:
  workflow_dispatch:
  pull_request:
    branches: stable
  schedule:
    - cron: '0 22 * * 5'

jobs:
  test_coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
        
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
          
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov
        
      - name: Run tests and coverage
        run: pytest --cov
