name: pytest-reporter workflow

on:
  workflow_dispatch:
  pull_request:
    branches: stable
  schedule:
    - cron: '0 22 * * *'

jobs:
  test_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
      - name: Run tests and coverage
        uses: lpenz/ghaction-pytest-cov@v1
