name: pytest-reporter workflow

on:
  workflow_dispatch:
  pull_request:
    branches: stable
  schedule:
    - cron: '0 22 * * *'

jobs:
  test_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install lenskit
          pip install implicit
          pip install Cython
          pip install scikit-surprise
          pip install pandas
          pip install PyYAML
          pip install rexmex
          pip install h5py
      - name: Run tests and coverage
        uses: lpenz/ghaction-pytest-cov@v1
        with:
          working-directory: /home/runner/work/fairreckitlib
