name: Pytest with Coverage

on:
  workflow_dispatch:
  pull_request:
    branches:
      - stable
      - dev
  schedule:
    - cron: '0 22 * * 5'

jobs:
  test_coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov
        
      - name: Run tests and coverage
        run: pytest --cov
