name: Pytest with Coverage

on:
  workflow_dispatch:
  pull_request:
    branches: stable
  schedule:
    - cron: '0 22 * * 5'

jobs:
  test_coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          cache: 'pip'
      - name: Run tests and coverage
        uses: lpenz/ghaction-pytest-cov@v1
